Repository likelion-plus/i-write-you, pull requests merged in 2024-01, with the labels that each got.

#1 style: emotion 적용 및 스타일 reset, 불필요 import문 삭제 등
  index.html
  src/App.css
  src/App.tsx
  src/index.css
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/RootLayout.tsx
  src/main.tsx
  src/pages/Home.tsx
  src/routes.tsx
  src/style/GlobalStyle.tsx
  tsconfig.json
Labels: 🎨Emotion

#5 🚀init: 초기 설정(페이지 생성, media query 추가, 공통 css width값)
  package.json
  pnpm-lock.yaml
  public/hotel.png
  public/mailTruck.png
  src/App.tsx
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/RootLayout.tsx
  src/pages/Hotel.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Received.tsx
  src/pages/ReceivedRead.tsx
  src/pages/Sent.tsx
  src/pages/SentRead.tsx
  src/pages/WriteImage.tsx
  src/pages/WriteInfo.tsx
  src/pages/WriteLetter.tsx
  src/pages/WritePassword.tsx
  src/routes.tsx
  src/style/Common.tsx
  src/style/GlobalStyle.tsx
  src/style/mq.tsx
Labels: ➕add, 🖌️Emotion, 🪗responsive

#11 feat/letterbox: 편지함 페이지들 마크업
  src/pages/Received.tsx
  src/pages/Sent.tsx
Labels: 🖌️Emotion, 🛠️markup

#12 🛠️ markup: Login Join 페이지 HTML/CSS 마크업 완성
  public/loginImage.png
  public/stamp.png
  src/pages/Join.tsx
  src/pages/Login.tsx
Labels: 🖌️Emotion, 🛠️markup, 🎨 style

#13 [html/css] 편지 쓰기 마크업 및 스타일
  gitmessage.txt
  public/bg/illust1.jpg
  public/bg/illust2.jpg
  public/bg/illust3.jpg
  public/bg/illust4.jpg
  public/bg/illust5.jpg
  public/bg/illust6.jpg
  public/bg/illust7.jpg
  public/bg/illust8.jpg
  public/bg/illust9.jpg
  src/pages/WriteImage.tsx
  src/pages/WriteInfo.tsx
  src/pages/WriteLetter.tsx
  src/style/mq.tsx
Labels: ➕add, 🖌️Emotion, 🛠️markup, 🎨 style

#14 메인페이지, 호텔개시페이지 마크업 및 스타일링
  package-lock.json
  package.json
  public/sliceHotel.png
  public/sliceNamePlate.png
  src/components/EventControl.tsx
  src/components/Mail.tsx
  src/components/MenuButton.tsx
  src/components/SeasonEvent.tsx
  src/pages/Hotel.tsx
  src/pages/Main.tsx
  src/recoil/atom/useOpen.ts
  src/style/GlobalStyle.tsx
  src/util/random.ts
  src/util/seasonAnimation.ts
Labels: 💙recoil, 🖌️Emotion, 🛠️markup, ✨feat
