Repository likelion-plus/i-write-you, pull requests merged in 2024-02, with the labels that each got.

#20 markup: friend 페이지 마크업
  public/back.png
  public/noPass.png
  public/pass.png
  src/components/FriendButton.tsx
  src/components/FriendList.tsx
  src/components/FriendNavButton.tsx
  src/components/FriendRequest.tsx
  src/components/FriendRequestForm.tsx
  src/pages/Friend.tsx
  src/routes.tsx
Labels: ➕add, 🖌️Emotion, 🛠️markup, 🎨 style

#21 편지 발송 기능 1차 완성
  .env
  package-lock.json
  package.json
  public/404.png
  public/bg/illust1.jpg
  public/bg/illust4.jpg
  public/bg/illust6.jpg
  public/bg/illust7.jpg
  public/bg/letter10.jpg
  public/bg/letter11.jpg
  public/bg/letter12.jpg
  public/bg/letter13.jpg
  public/bg/letter14.jpg
  public/bg/letter15.jpg
  public/bg/letter16.jpg
  public/bg/letter17.jpg
  public/bg/letter18.jpg
  public/bg/letter19.jpg
  public/bg/letter2.jpg
  public/bg/letter20.jpg
  public/bg/letter21.jpg
  public/bg/letter22.jpg
  public/bg/letter23.jpg
  public/bg/letter24.jpg
  public/bg/letter26.jpg
  public/bg/letter27.jpg
  public/bg/letter3.jpg
  public/bg/letter4.jpg
  public/bg/letter5.jpg
  public/bg/letter6.jpg
  public/bg/letter7.jpg
  public/bg/letter8.jpg
  public/bg/letter9.jpg
  public/hotel.png
  public/loading.png
  public/secretCode.png
  public/selectDown.png
  public/selectUp.png
  public/sliceHotel.png
  public/sliceNamePlate.png
  public/vite.svg
  src/client.ts
  src/components/Loading.tsx
  src/components/MenuButton.tsx
  src/components/SelectWritingPad.tsx
  src/components/ShareModal.tsx
  src/layout/RootLayout.tsx
  src/pages/Hotel.tsx
  src/pages/Main.tsx
  src/pages/NonMember.tsx
  src/pages/NotFound.tsx
  src/pages/WriteInfo.tsx
  src/pages/WriteLetter.tsx
  src/recoil/atom/useLetter.ts
  src/style/GlobalStyle.tsx
  src/util/clickAnimation.ts
  src/vite-env.d.ts
Labels: ⚡supabase, ✨feat

#23 보낸편지함 페이지 기능 1차 완성
  pnpm-lock.yaml
  public/frontMan.png
  src/pages/Sent.tsx
  src/types/Database.ts
  src/util/debounce.ts
  src/util/letterSentRecent.ts
  src/util/throttle.ts
Labels: ➕add, 💻typescript, ⚡supabase, 🖌️Emotion, ✨feat
