Repository likelion-plus/i-write-you, pull requests merged in 2024-03, with the labels that each got.

#26 feat: 보낸/받는편지함 페이지 페이지네이션 기능 구현
  src/components/LetterPagination.tsx
  src/components/MenuButton.tsx
  src/pages/Received.tsx
  src/pages/Sent.tsx
Labels: ➕add, 💻typescript, 🖌️Emotion, 🌟react, ✨feat

#27 feat: 호텔 페이지 호텔 이름 출력 및 미설정 시 페이지 이동 등
  src/pages/Hotel.tsx
  src/pages/MyProfile.tsx
Labels: 🐛bug

#29 [동호님 확인필요!] Develop 병합
  src/components/ShareModal.tsx
  src/pages/NonMember.tsx
  src/pages/WriteImage.tsx
  src/pages/WriteInfo.tsx
  src/pages/WriteLetter.tsx
  src/pages/WritePassword.tsx
  src/routes.tsx
Labels: 🐛bug

#31 feat: 호텔 이름 설정, 토스트 전역 적용, 메뉴 추가
  src/App.tsx
  src/components/MenuButton.tsx
  src/pages/MyProfile.tsx
Labels: ✨feat, 🎨 style

#32 friend목록 기능 추가
  src/components/FriendButton.tsx
  src/components/FriendList.tsx
  src/components/FriendReceived.tsx
  src/components/FriendRequest.tsx
  src/components/FriendRequestForm.tsx
  src/pages/Friend.tsx
  src/recoil/atom/useFriend.ts
  src/vite-env.d.ts
Labels: ➕add, 💙recoil, 💻typescript, ⚡supabase, 🌟react, 💿local storage, ✨feat

#33 수신인 발신인 아이디 추가
  src/pages/WriteInfo.tsx
  src/pages/WriteLetter.tsx
  src/recoil/atom/useLetter.ts
Labels: ✍️documentation

#34 feat: 호텔개시 페이지 '편지 확인 유무' 기능 구현
  src/components/Mail.tsx
  src/pages/Hotel.tsx
  src/pages/ReceivedRead.tsx
  src/types/Database.ts
Labels: 💻typescript, ⚡supabase, 🚨help, ✨feat, 📬 API
