Repository likelion-plus/i-write-you, pull requests merged in 2024-05, with the labels that each got.

#49 타입 수정 및 로그인폼 연결 수정
  src/components/FriendList.tsx
  src/layout/RootLayout.tsx
  src/pages/NonMember.tsx
Labels: ✍️documentation

#52 [2024.05.02] develop에서 main으로 merge
  .env
  package.json
  pnpm-lock.yaml
  src/components/FriendButton.tsx
  src/components/FriendList.tsx
  src/components/FriendNavButton.tsx
  src/components/FriendReceived.tsx
  src/components/FriendRequestForm.tsx
  src/components/Loading.tsx
  src/components/Mail.tsx
  src/components/MenuButton.tsx
  src/layout/RootLayout.tsx
  src/pages/Friend.tsx
  src/pages/Hotel.tsx
  src/pages/MyProfile.tsx
  src/pages/NonMember.tsx
  src/pages/NotFound.tsx
  src/pages/Read.tsx
  src/pages/Received.tsx
  src/pages/ReceivedRead.tsx
  src/pages/Sent.tsx
  src/pages/SentRead.tsx
  src/pages/WriteInfo.tsx
  src/pages/WriteLetter.tsx
  src/recoil/atom/useFriend.ts
  src/recoil/atom/useLetter.ts
  src/routes.tsx
  src/vite-env.d.ts
Labels: 🌏deploy

#54 호텔페이지 편지함 UI 재수정
  src/components/Mail.tsx
  src/components/MenuButton.tsx
  src/pages/Hotel.tsx
Labels: 🪗responsive, 🎨 style

#56 반응형 수정
  src/components/MenuButton.tsx
  src/pages/Friend.tsx
  src/pages/MyProfile.tsx
Labels: 🖌️Emotion

#57 받는/보낸편지함 페이지 UI 수정
  src/pages/Received.tsx
  src/pages/Sent.tsx
Labels: 🪗responsive, ✨feat, 🎨 style

#58 [2024.05.25] develop에서 main으로 merge
  src/components/Mail.tsx
  src/components/MenuButton.tsx
  src/pages/Friend.tsx
  src/pages/Hotel.tsx
  src/pages/MyProfile.tsx
  src/pages/Received.tsx
  src/pages/Sent.tsx
Labels: 🌏deploy

#59 페이지네이션 에러 수정
  src/pages/Received.tsx
  src/pages/Sent.tsx
Labels: 🗝️fix
