Repository likelion-plus/i-write-you, pull requests merged in 2024-04, with the labels that each got.

#38 feat: 받는/보낸 편지함 페이지 데이터 사용자화
  src/pages/Hotel.tsx
  src/pages/Received.tsx
  src/pages/ReceivedRead.tsx
  src/pages/Sent.tsx
Labels: 💙recoil, 🤖refactor

#39 fix/feat: 호텔 페이지 빈 편지함 에러 해결 및 조건별 편지 태그 분리
  src/components/Mail.tsx
  src/pages/Hotel.tsx
Labels: ✨feat, 🗝️fix

#43 feat: 편지 읽는 페이지 마크업, 레이아웃 스타일링 및 기능 구현
  src/components/Mail.tsx
  src/pages/Hotel.tsx
  src/pages/Read.tsx
  src/pages/Received.tsx
  src/pages/ReceivedRead.tsx
  src/pages/Sent.tsx
  src/pages/SentRead.tsx
  src/routes.tsx
Labels: 💙recoil, 🖌️Emotion, 🌟react, 🚗react router, 🛠️markup, ✨feat, 📬 API

#44 fix/feat: 편지 읽는 페이지 접근성, 가독성 향상
  src/pages/Hotel.tsx
  src/pages/Read.tsx
Labels: 🌟react, ✨feat, 🗝️fix

#45 crypto 브랜치 추가 및 작업
  .env
  package.json
  pnpm-lock.yaml
  src/pages/NonMember.tsx
  src/pages/WriteInfo.tsx
  src/pages/WriteLetter.tsx
  src/recoil/atom/useLetter.ts
  src/vite-env.d.ts
Labels: ✨feat

#46 [기능 구현] 친구 목록 검색 기능, 필터링 구현 및 프로필 설정 미변경 처리
  src/components/FriendButton.tsx
  src/components/FriendList.tsx
  src/components/FriendNavButton.tsx
  src/components/FriendReceived.tsx
  src/components/FriendRequestForm.tsx
  src/components/Loading.tsx
  src/components/MenuButton.tsx
  src/pages/Friend.tsx
  src/pages/MyProfile.tsx
  src/pages/NotFound.tsx
  src/recoil/atom/useFriend.ts
Labels: 💻typescript, ✨feat, 🎨 style, 🗝️fix

#47 편지 읽기 페이지 '답장하기' 버튼 기능 구현
  src/pages/Hotel.tsx
  src/pages/Read.tsx
  src/pages/Received.tsx
  src/pages/Sent.tsx
Labels: 💙recoil, ✨feat, 🗝️fix

#48 편지 읽기 페이지 첨부파일 기본 확장자 허용
  src/pages/Read.tsx
Labels: ✨feat
